'use client';
import { useEffect,useMemo,useState } from 'react';
type Step={delayDays:number;subject:string;body:string};
export default function CampaignsPage(){
 const [campaigns,setCampaigns]=useState<any[]>([]),[leads,setLeads]=useState<any[]>([]),[selected,setSelected]=useState<string[]>([]);
 const [name,setName]=useState(''),[dailyLimit,setDailyLimit]=useState(25),[campaignId,setCampaignId]=useState(''),[message,setMessage]=useState('');
 const [steps,setSteps]=useState<Step[]>([{delayDays:0,subject:'A quick idea for {{business_name}}',body:'Hi there,\n\nI came across your business while researching companies I may be able to help. I have one specific idea for improving lead response and follow-up. Would a brief conversation this week be unreasonable?'}]);
 const load=async()=>{const [c,l]=await Promise.all([fetch('/api/campaigns').then(r=>r.json()),fetch('/api/leads').then(r=>r.json())]);setCampaigns(c.campaigns||[]);setLeads((l.leads||[]).filter((x:any)=>x.email));}; useEffect(()=>{load()},[]);
 const active=useMemo(()=>campaigns.filter(c=>c.status==='ACTIVE'),[campaigns]);
 async function create(){setMessage('Saving...');const r=await fetch('/api/campaigns',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name,dailyLimit,steps})});const d=await r.json();setMessage(r.ok?'Campaign created':d.error||'Unable to create');if(r.ok){setName('');await load();}}
 async function activate(id:string){await fetch('/api/campaigns',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'activate',campaignId:id})});await load();}
 async function researchDraft(){if(selected.length!==1)return;setMessage('Researching lead and drafting...');const r=await fetch('/api/campaigns/generate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({leadId:selected[0]})});const d=await r.json();if(r.ok&&d.subject&&d.body){setSteps(steps.map((x,i)=>i===0?{...x,subject:d.subject,body:d.body}:x));setMessage(`Draft created with ${Array.isArray(d.factsUsed)?d.factsUsed.length:0} grounded facts`);}else setMessage(d.error||'Unable to generate draft');}
 async function enroll(){if(!campaignId||!selected.length)return;setMessage('Enrolling leads...');const r=await fetch('/api/campaigns/enroll',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({campaignId,leadIds:selected})});const d=await r.json();const ok=(d.results||[]).filter((x:any)=>x.ok).length;setMessage(`${ok} lead${ok===1?'':'s'} enrolled`);setSelected([]);await load();}
 return <main className="mx-auto max-w-6xl space-y-6 p-6"><div><h1 className="text-3xl font-semibold text-white">Email Campaigns</h1><p className="mt-2 text-zinc-400">Low-volume, research-led sequences with daily caps, CRM logging, and permanent unsubscribe suppression.</p></div>
 <section className="rounded-2xl border border-zinc-800 bg-zinc-950 p-5"><h2 className="text-xl font-medium text-white">Create a sequence</h2><div className="mt-4 grid gap-4 md:grid-cols-2"><label className="text-sm text-zinc-300">Campaign name<input className="mt-1 w-full rounded-lg border border-zinc-700 bg-zinc-900 p-3" value={name} onChange={e=>setName(e.target.value)}/></label><label className="text-sm text-zinc-300">Daily limit<input type="number" min={1} max={100} className="mt-1 w-full rounded-lg border border-zinc-700 bg-zinc-900 p-3" value={dailyLimit} onChange={e=>setDailyLimit(Number(e.target.value))}/></label></div>
 {steps.map((s,i)=><div key={i} className="mt-5 rounded-xl border border-zinc-800 p-4"><div className="grid gap-3 md:grid-cols-4"><label className="text-sm text-zinc-400">Delay days<input type="number" className="mt-1 w-full rounded bg-zinc-900 p-2" value={s.delayDays} onChange={e=>setSteps(steps.map((x,j)=>j===i?{...x,delayDays:Number(e.target.value)}:x))}/></label><label className="md:col-span-3 text-sm text-zinc-400">Subject<input className="mt-1 w-full rounded bg-zinc-900 p-2" value={s.subject} onChange={e=>setSteps(steps.map((x,j)=>j===i?{...x,subject:e.target.value}:x))}/></label></div><textarea rows={6} className="mt-3 w-full rounded bg-zinc-900 p-3" value={s.body} onChange={e=>setSteps(steps.map((x,j)=>j===i?{...x,body:e.target.value}:x))}/></div>)}
 <div className="mt-4 flex flex-wrap gap-3"><button className="rounded-lg bg-zinc-800 px-4 py-2" onClick={()=>setSteps([...steps,{delayDays:3,subject:'',body:''}])}>Add step</button><button className="rounded-lg bg-blue-600 px-4 py-2 font-medium" onClick={create}>Create campaign</button><span className="py-2 text-sm text-zinc-400">{message}</span></div></section>
 <section className="space-y-3"><h2 className="text-xl font-medium text-white">Campaigns</h2>{campaigns.map(c=><div key={c.id} className="flex items-center justify-between rounded-xl border border-zinc-800 bg-zinc-950 p-4"><div><div className="font-medium text-white">{c.name}</div><div className="text-sm text-zinc-400">{c.status} · {c.active_count||0} active · {c.enrolled_count||0} enrolled · {c.daily_limit}/day</div></div>{c.status!=='ACTIVE'&&<button onClick={()=>activate(c.id)} className="rounded-lg bg-emerald-600 px-4 py-2">Activate</button>}</div>)}</section>
 <section className="rounded-2xl border border-zinc-800 bg-zinc-950 p-5"><h2 className="text-xl font-medium text-white">Enroll leads</h2><div className="mt-4 flex gap-3"><select className="min-w-72 rounded-lg bg-zinc-900 p-3" value={campaignId} onChange={e=>setCampaignId(e.target.value)}><option value="">Select active campaign</option>{active.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><button className="rounded-lg bg-violet-600 px-4 py-2 disabled:opacity-40" disabled={selected.length!==1} onClick={researchDraft}>Research draft for selected lead</button><button className="rounded-lg bg-blue-600 px-4 py-2 disabled:opacity-40" disabled={!campaignId||!selected.length} onClick={enroll}>Enroll selected ({selected.length})</button></div><div className="mt-4 max-h-96 overflow-auto rounded-xl border border-zinc-800">{leads.map(l=><label key={l.id} className="flex cursor-pointer items-center gap-3 border-b border-zinc-800 p-3 text-sm"><input type="checkbox" checked={selected.includes(l.id)} onChange={e=>setSelected(e.target.checked?[...selected,l.id]:selected.filter(id=>id!==l.id))}/><span className="font-medium text-white">{l.businessName}</span><span className="text-zinc-400">{l.email}</span></label>)}</div></section></main>
}
